# Generated by Django 4.2.7 on 2024-05-30 06:26

import context_layer_management.models.layer_upload
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of data.', max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_ready', models.BooleanField(default=False, help_text='Indicates if the layer is ready.')),
                ('type', models.CharField(choices=[('Vector Tile', 'Vector Tile'), ('Raster Tile', 'Raster Tile')], default='Vector Tile', max_length=256)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LayerUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Start', 'Start'), ('Running', 'Running'), ('Failed', 'Failed'), ('Success', 'Success')], default='Start', max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('folder', models.TextField(default=context_layer_management.models.layer_upload.generate_folder)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_layer_management.layer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LayerStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of data.', max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('style', models.JSONField(help_text='Contains mapbox style information.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LayerField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_layer_management.layer')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='default_style',
            field=models.ForeignKey(blank=True, help_text='Default layer style', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_style', to='context_layer_management.layerstyle'),
        ),
        migrations.AddField(
            model_name='layer',
            name='styles',
            field=models.ManyToManyField(blank=True, help_text='Style list for the layer.', to='context_layer_management.layerstyle'),
        ),
    ]
