# Specific configuration for development environment

volumes:
  static-data:
  media-data:

# Exactly the same as production but for dev env, we expose the port and uses
# different port for the web.
version: '3.4'
services:

  dev:
    image: ${APP_IMAGE}:dev
    container_name: "dev"
    links:
      - db
      - redis
    volumes:
      - static-data:/home/web/static
      - media-data:/home/web/media
      - ./docker/Dockerfile:/home/web/django_project/Dockerfile
      - ./docker/requirements.txt:/home/web/django_project/requirements.txt
      - ./docker/requirements-dev.txt:/home/web/django_project/requirements-dev.txt
      - ./production_prep_check.py:/home/web/django_project/production_prep_check.py
    environment:
      # editable in .env
      - DATABASE_NAME=django
      - DATABASE_USERNAME=docker
      - DATABASE_PASSWORD=docker
      - DATABASE_HOST=db
      - RABBITMQ_HOST=rabbitmq
      - DJANGO_SETTINGS_MODULE=core.settings.test
      - SECRET_KEY=SECRET_KEY

      # Redis config
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis_password

      # Email where alters should be sent. This will be used by let's encrypt and as the django admin email.
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=admin@example.com
      - SENTRY_DSN=
      - SENTRY_ENVIRONMENT=staging
    entrypoint: [ ]
    ports:
      # for django test server
      - "5000:5000"