version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/opt/postgres/data

  worker:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    volumes:
      - ../:/home/web/project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media

  dev:
    image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    entrypoint: []
    volumes:
      - ../:/home/web/project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
    links:
      - db
      - worker

  django:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: vscode
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media

