# Generated by Django 4.2.16 on 2024-10-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_native_gis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='pmtile',
            field=models.FileField(blank=True, help_text='Optional PMTile file associated with the layer.', null=True, upload_to='pmtile_files/'),
        ),
    ]
