# Generated by Django 4.2.7 on 2025-12-22 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud_native_gis', '0002_layer_pmtile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Start', 'Start'), ('Running', 'Running'), ('Failed', 'Failed'), ('Success', 'Success')], default='Start', max_length=100)),
                ('note', models.TextField(blank=True, help_text='Note of the download task', null=True)),
                ('file_type', models.CharField(choices=[('original', 'original'), ('geojson', 'geojson'), ('kml', 'kml'), ('shapefile', 'shapefile'), ('geopackage', 'geopackage')], max_length=256)),
                ('working_dir', models.TextField()),
                ('filename', models.TextField(blank=True, null=True)),
                ('task_id', models.TextField(blank=True, help_text='Celery task id', null=True)),
                ('path', models.TextField(blank=True, help_text='Generated path to file on server', null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_native_gis.layer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
