# Generated by Django 4.2.7 on 2026-06-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_native_gis', '0003_layerdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='extent',
            field=models.JSONField(blank=True, help_text='Bounding box [xmin, ymin, xmax, ymax] in EPSG:4326.', null=True),
        ),
    ]
