name: 📖 Documentation
on:
  push:
    branches:
      - main
      - docs
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - ".github/workflows/BuildMKDocsAndPublishToGithubPages.yml"
      - "docs/**.md"
      - "docs/**.py"
      - "docs/assets/**"
  pull_request:
  # Allow manually running in the actions tab
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.head_ref == 'docs-fix'
    steps:
      - name: Checkout main from github
        uses: actions/checkout@v4

      - name: Create Mkdocs Config 🚀
        working-directory: ./docs
        run: ./create-mkdocs-html-config.sh

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r docs/requirements.txt


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
