name: 📖 Documentation
on:
  push:
    branches:
      - main
      - docs
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - ".github/workflows/BuildMKDocsAndPublishToGithubPages.yml"
      - "docs/**.md"
      - "docs/**.py"
      - "docs/assets/**"
  # Allow manually running in the actions tab
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main from github
        uses: actions/checkout@v1
      - name: Create Mkdocs Config 🚀
        working-directory: ./docs
        run: ./create-mkdocs-html-config.sh
      - name: Deploy docs to github pages
        # This is where we get the material theme from
        uses: timlinux/mkdocs-deploy-gh-pages@master
        # Wrong
        #uses: timlinux/QGISAnimationWorkbench@main
        env:
          # Read this carefully:
          # https://github.com/marketplace/actions/deploy-mkdocs#building-with-github_token
          # The token is automatically generated by the GH Action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_DIRECTORY: docs
          CONFIG_FILE: docs/mkdocs.yml
          REQUIREMENTS: docs/requirements.txt
